import { Command } from 'commander';

const MASTER_TEMPLATES = {
  'saas-starter': {
    id: 'saas-starter',
    name: 'SaaS Multi-Tenant Starter Kit',
    description: 'Boilerplate layout initializing user billing profiles, subscription product tiers, and private document buckets.',
    schemaSql: `
      CREATE TABLE IF NOT EXISTS public.profiles (
        id UUID PRIMARY KEY,
        full_name TEXT,
        billing_tier TEXT DEFAULT 'free',
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );
      ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
    `,
    cleanupSql: 'DROP TABLE IF EXISTS public.profiles CASCADE;'
  },
  'chat-app': {
    id: 'chat-app',
    name: 'Real-time Chat Layout',
    description: 'Instant communication layout with channels and message row RLS isolation rules.',
    schemaSql: `
      CREATE TABLE IF NOT EXISTS public.channels (id UUID PRIMARY KEY, name TEXT);
      CREATE TABLE IF NOT EXISTS public.messages (id UUID PRIMARY KEY, content TEXT);
    `,
    cleanupSql: 'DROP TABLE IF EXISTS public.messages CASCADE; DROP TABLE IF EXISTS public.channels CASCADE;'
  }
};

export const registerTemplateCommand = (program: Command) => {

  // 1. Standalone Command: template-list
  program
    .command('template-list')
    .description('List all available one-click project blueprints')
    .action(() => {
      console.log('\n📋 Available InsForge Project Templates:');
      console.log('---------------------------------------------------------');
      Object.values(MASTER_TEMPLATES).forEach(t => {
        console.log(`✨ Template Key: \x1b[36m${t.id}\x1b[0m`);
        console.log(`   Name:        ${t.name}`);
        console.log(`   Description: ${t.description}\n`);
      });
    });

  // 2. Standalone Command: template-apply
  program
    .command('template-apply')
    .description('Provision a blueprint template setup onto your target environment')
    .requiredOption('--id <key>', 'The template identifier key (e.g., saas-starter, chat-app)')
    .option('--env <string>', 'Database connection string override target', 'postgresql://postgres:postgres@localhost:5432/insforge')
    .option('--dry-run', 'Preview precisely what resources will be created without modifying state')
    .action(async (options) => {
      const template = (MASTER_TEMPLATES as any)[options.id];
      if (!template) {
        console.error(`💥 Error: Template ID [${options.id}] does not exist.`);
        process.exit(1);
      }

      console.log(`\n🔎 Pre-Flight Resource Impact Summary for [${template.name}]:`);
      console.log('---------------------------------------------------------');
      console.log(`📦 Schema Tables: Configured to deploy via DDL transaction`);
      console.log('---------------------------------------------------------');

      if (options.dryRun) {
        console.log('👀 [DRY-RUN COMPLETE]: No remote state changes were made.');
        return;
      }

      console.log(`🚀 Initiating state provisioning on destination environment...`);
      
      const { Client } = await import('pg');
      const client = new Client({ connectionString: options.env });
      
      try {
        await client.connect();
        await client.query('BEGIN');
        await client.query(template.schemaSql);
        await client.query('COMMIT');
        
        console.log(`\n🟢 [SUCCESS]: '${template.name}' applied successfully!\n`);
        console.log('💡 Cleanup Guidance:');
        console.log(`npx tsx packages/cli/src/index.ts template-cleanup --id ${options.id}\n`);
      } catch (err: any) {
        console.error(`💥 Error applying blueprint: ${err.message}`);
        process.exit(1);
      } finally {
        await client.end();
      }
    });

  // 3. Standalone Command: template-cleanup
  program
    .command('template-cleanup')
    .description('Reset and scrub away resources provisioned by a template')
    .requiredOption('--id <key>', 'The template identifier key to clear out')
    .option('--env <string>', 'Database target connection string environment', 'postgresql://postgres:postgres@localhost:5432/insforge')
    .action(async (options) => {
      const template = (MASTER_TEMPLATES as any)[options.id];
      if (!template) {
        console.error(`💥 Error: Template ID [${options.id}] not found.`);
        process.exit(1);
      }
      
      console.log(`🗑️  Scrubbing resources generated by template [${options.id}]...`);
      
      const { Client } = await import('pg');
      const client = new Client({ connectionString: options.env });
      try {
        await client.connect();
        await client.query('BEGIN');
        await client.query(template.cleanupSql);
        await client.query('COMMIT');
        console.log(`✨ [CLEANUP COMPLETE]: Template dropped cleanly.`);
      } catch (err: any) {
        console.error(`💥 Error running cleanup protocol: ${err.message}`);
        process.exit(1);
      } finally {
        await client.end();
      }
    });
};